    //------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaMVC.Models
{
    using System; 
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class appointments
    {
        public int idAppointment { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Date")]
        public System.DateTime dateHour { get; set; }
        [Required]
        [Display(Name = "Sujet")]
        public string subject { get; set; }
        [Display(Name = "Client")]
        public int idCustomer { get; set; }
        [Display(Name = "Courtier")]
        public int idBroker { get; set; }
    
        public virtual brokers brokers { get; set; }
        public virtual customers customers { get; set; }
    }
}
